//! Integration tests for Cargo dependency-declaration extraction and
//! `eg query manifest-deps` (issue #180): every directly-declared Cargo dependency
//! becomes a deterministic, citable graph fact — name, kind, declared
//! requirement, resolved locked version, declaring package, and manifest
//! handle — derived locally and read-only, never via `cargo metadata`.

#![allow(missing_docs)]

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use aletheia_egregore::scan_repository_at_with_override;
use assert_cmd::Command;
use serde_json::Value;

const FIXED_TIME: &str = "2026-07-01T00:00:00Z";

fn egregore() -> Command {
    Command::cargo_bin("egregore").expect("binary should be built")
}

// ---------------------------------------------------------------------------
// Fixture: a two-member workspace with a committed Cargo.lock
// ---------------------------------------------------------------------------

/// Virtual workspace root: no `[package]`, no dependency tables — must
/// produce zero dependency facts and zero diagnostics.
const ROOT_MANIFEST: &str = r#"[workspace]
members = ["crates/pkg-a", "crates/local-b"]
"#;

/// First member: all three dependency tables, a path dependency without a
/// version requirement, a dependency missing from the lockfile, and a
/// dependency locked at two different versions.
const PKG_A_MANIFEST: &str = r#"[package]
name = "pkg-a"
version = "0.1.0"

[dependencies]
serde = "1.0.228"
local-b = { path = "../local-b" }
ghost = "0.9"
dupes = "1"

[dev-dependencies]
tempfile = "3"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
"#;

/// Second member: one normal dependency shared with pkg-a.
const LOCAL_B_MANIFEST: &str = r#"[package]
name = "local-b"
version = "0.1.0"

[dependencies]
serde = "1.0.228"
"#;

/// Committed lockfile: `serde`, `tempfile`, `cc`, and `local-b` resolve to a
/// single version; `dupes` is locked at two versions (ambiguous); `ghost`
/// is absent entirely.
const CARGO_LOCK: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "cc"
version = "1.0.100"

[[package]]
name = "dupes"
version = "1.0.0"

[[package]]
name = "dupes"
version = "2.0.3"

[[package]]
name = "local-b"
version = "0.1.0"

[[package]]
name = "pkg-a"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.228"

[[package]]
name = "tempfile"
version = "3.27.0"
"#;

fn write_fixture(dir: &Path) {
    fs::create_dir_all(dir.join("crates/pkg-a/src")).expect("pkg-a dir");
    fs::create_dir_all(dir.join("crates/local-b/src")).expect("local-b dir");
    fs::write(dir.join("Cargo.toml"), ROOT_MANIFEST).expect("root manifest");
    fs::write(dir.join("Cargo.lock"), CARGO_LOCK).expect("lockfile");
    fs::write(dir.join("crates/pkg-a/Cargo.toml"), PKG_A_MANIFEST).expect("pkg-a manifest");
    fs::write(dir.join("crates/local-b/Cargo.toml"), LOCAL_B_MANIFEST).expect("local-b manifest");
    fs::write(dir.join("crates/pkg-a/src/lib.rs"), "pub fn a() {}\n").expect("pkg-a lib");
    fs::write(dir.join("crates/local-b/src/lib.rs"), "pub fn b() {}\n").expect("local-b lib");
}

/// Scans the workspace fixture and writes the JSONL graph. Returns
/// (`TempDir`, graph path). The graph is written *outside* the fixture tree
/// so read-only assertions can hash the fixture exactly.
fn fixture_graph() -> (tempfile::TempDir, PathBuf) {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("deps-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");
    (temp, graph)
}

/// Parses every `DependencyDeclaration` node record from a graph JSONL.
fn dependency_nodes(graph: &Path) -> Vec<Value> {
    fs::read_to_string(graph)
        .expect("graph must be readable")
        .lines()
        .map(|line| serde_json::from_str::<Value>(line).expect("valid record JSON"))
        .filter(|record| record["kind"] == "DependencyDeclaration")
        .collect()
}

fn run_query_deps(graph: &Path, extra: &[&str]) -> Value {
    let output = egregore()
        .args(["query", "manifest-deps", "--graph"])
        .arg(graph)
        .args(extra)
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    serde_json::from_str(std::str::from_utf8(&output).expect("utf8").trim())
        .expect("stdout must be valid JSON")
}

fn declaration<'a>(parsed: &'a Value, package: &str, kind: &str, name: &str) -> &'a Value {
    parsed["declarations"]
        .as_array()
        .expect("declarations array")
        .iter()
        .find(|d| {
            d["declaring_package"] == package && d["dependency_kind"] == kind && d["name"] == name
        })
        .unwrap_or_else(|| panic!("missing declaration ({package}, {kind}, {name})"))
}

// ---------------------------------------------------------------------------
// AC1: one deterministic fact per (declaring package, name, kind)
// ---------------------------------------------------------------------------

#[test]
fn scan_captures_one_fact_per_declared_dependency() {
    let (_temp, graph) = fixture_graph();
    let nodes = dependency_nodes(&graph);

    let mut keys: Vec<(String, String, String)> = nodes
        .iter()
        .map(|n| {
            (
                n["dependency"]["declaring_package"]
                    .as_str()
                    .expect("declaring_package")
                    .to_owned(),
                n["dependency"]["dependency_kind"]
                    .as_str()
                    .expect("dependency_kind")
                    .to_owned(),
                n["name"].as_str().expect("name").to_owned(),
            )
        })
        .collect();
    keys.sort();
    let expected: Vec<(String, String, String)> = [
        ("local-b", "normal", "serde"),
        ("pkg-a", "build", "cc"),
        ("pkg-a", "dev", "tempfile"),
        ("pkg-a", "normal", "dupes"),
        ("pkg-a", "normal", "ghost"),
        ("pkg-a", "normal", "local-b"),
        ("pkg-a", "normal", "serde"),
    ]
    .iter()
    .map(|(p, k, n)| ((*p).to_owned(), (*k).to_owned(), (*n).to_owned()))
    .collect();
    assert_eq!(keys, expected, "exactly one fact per declaration");
}

// ---------------------------------------------------------------------------
// AC2: each fact carries name, kind, requirement, resolved version,
//       declaring package, and the manifest handle
// ---------------------------------------------------------------------------

#[test]
fn facts_carry_requirement_resolution_and_manifest_handle() {
    let (_temp, graph) = fixture_graph();
    let nodes = dependency_nodes(&graph);

    let serde_a = nodes
        .iter()
        .find(|n| n["name"] == "serde" && n["dependency"]["declaring_package"] == "pkg-a")
        .expect("pkg-a serde fact");
    assert_eq!(serde_a["repo_relative_path"], "crates/pkg-a/Cargo.toml");
    assert_eq!(serde_a["dependency"]["dependency_kind"], "normal");
    assert_eq!(serde_a["dependency"]["declared_requirement"], "1.0.228");
    assert_eq!(serde_a["dependency"]["resolved_version"], "1.0.228");
    assert_eq!(serde_a["dependency"]["resolution"], "locked");
    assert!(
        serde_a["id"]
            .as_str()
            .expect("stable record id")
            .starts_with("codegraph:v"),
        "dependency facts carry stable codegraph record IDs"
    );

    // Inline-table declaration: requirement is the `version` key as written.
    let cc = nodes
        .iter()
        .find(|n| n["name"] == "cc")
        .expect("cc build-dependency fact");
    assert_eq!(cc["dependency"]["dependency_kind"], "build");
    assert_eq!(cc["dependency"]["declared_requirement"], "1.0");
    assert_eq!(cc["dependency"]["resolved_version"], "1.0.100");

    // Path dependency without a version key: no fabricated requirement.
    let local_b = nodes
        .iter()
        .find(|n| n["name"] == "local-b" && n["kind"] == "DependencyDeclaration")
        .expect("local-b path-dependency fact");
    assert!(
        local_b["dependency"]["declared_requirement"].is_null(),
        "path dependency without a version key must not fabricate a requirement"
    );
    assert_eq!(local_b["dependency"]["resolved_version"], "0.1.0");
    assert_eq!(local_b["dependency"]["resolution"], "locked");
}

// ---------------------------------------------------------------------------
// AC3: lockfile-miss and ambiguity markers — never a guessed version
// ---------------------------------------------------------------------------

#[test]
fn lockfile_misses_are_marked_never_fabricated() {
    let (_temp, graph) = fixture_graph();
    let nodes = dependency_nodes(&graph);

    let ghost = nodes
        .iter()
        .find(|n| n["name"] == "ghost")
        .expect("ghost fact");
    assert_eq!(ghost["dependency"]["resolution"], "not_in_lockfile");
    assert!(ghost["dependency"]["resolved_version"].is_null());

    let dupes = nodes
        .iter()
        .find(|n| n["name"] == "dupes")
        .expect("dupes fact");
    assert_eq!(dupes["dependency"]["resolution"], "ambiguous_in_lockfile");
    assert!(
        dupes["dependency"]["resolved_version"].is_null(),
        "two locked versions must never be collapsed into a guess"
    );
}

#[test]
fn absent_lockfile_marks_every_fact_unresolved() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    fs::remove_file(repo.join("Cargo.lock")).expect("drop the lockfile");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("deps-fixture"))
        .expect("fixture should scan without a lockfile")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let nodes = dependency_nodes(&graph);
    assert!(
        !nodes.is_empty(),
        "declared facts survive a missing lockfile"
    );
    for node in &nodes {
        assert_eq!(
            node["dependency"]["resolution"], "no_lockfile",
            "every fact carries the documented unresolved marker"
        );
        assert!(
            node["dependency"]["resolved_version"].is_null(),
            "no fabricated resolved version without a lockfile"
        );
    }
    // Declared requirements are still captured as written.
    let serde_fact = nodes
        .iter()
        .find(|n| n["name"] == "serde" && n["dependency"]["declaring_package"] == "pkg-a")
        .expect("serde fact");
    assert_eq!(serde_fact["dependency"]["declared_requirement"], "1.0.228");
}

// ---------------------------------------------------------------------------
// AC4: `eg query manifest-deps` lists declarations and answers a direct lookup
// ---------------------------------------------------------------------------

#[test]
fn query_deps_lists_every_declaration_with_stable_ordering() {
    let (_temp, graph) = fixture_graph();
    let parsed = run_query_deps(&graph, &[]);

    assert_eq!(parsed["ok"], true);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(declarations.len(), 7, "all seven declared dependencies");
    assert_eq!(parsed["count"], 7);

    // Deterministic ordering: manifest path, declaring package, kind
    // (normal < dev < build), then name.
    let order: Vec<(String, String, String)> = declarations
        .iter()
        .map(|d| {
            (
                d["manifest_path"]
                    .as_str()
                    .expect("manifest_path")
                    .to_owned(),
                d["dependency_kind"].as_str().expect("kind").to_owned(),
                d["name"].as_str().expect("name").to_owned(),
            )
        })
        .collect();
    let expected: Vec<(String, String, String)> = [
        ("crates/local-b/Cargo.toml", "normal", "serde"),
        ("crates/pkg-a/Cargo.toml", "normal", "dupes"),
        ("crates/pkg-a/Cargo.toml", "normal", "ghost"),
        ("crates/pkg-a/Cargo.toml", "normal", "local-b"),
        ("crates/pkg-a/Cargo.toml", "normal", "serde"),
        ("crates/pkg-a/Cargo.toml", "dev", "tempfile"),
        ("crates/pkg-a/Cargo.toml", "build", "cc"),
    ]
    .iter()
    .map(|(m, k, n)| ((*m).to_owned(), (*k).to_owned(), (*n).to_owned()))
    .collect();
    assert_eq!(order, expected, "stable documented ordering");

    // Every row is a citable fact.
    for d in declarations {
        assert!(d["record_id"].as_str().is_some(), "row needs record_id");
        assert!(d["manifest_path"].as_str().is_some(), "row needs handle");
        assert!(d["declaring_package"].as_str().is_some());
        assert!(d["resolution"].as_str().is_some());
    }
}

#[test]
fn query_deps_answers_a_direct_name_lookup() {
    let (_temp, graph) = fixture_graph();
    let parsed = run_query_deps(&graph, &["--name", "serde"]);

    assert_eq!(parsed["ok"], true);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(
        declarations.len(),
        2,
        "serde is declared by both member crates"
    );
    for d in declarations {
        assert_eq!(d["name"], "serde");
        assert_eq!(d["resolved_version"], "1.0.228");
    }
    let a = declaration(&parsed, "pkg-a", "normal", "serde");
    assert_eq!(a["manifest_path"], "crates/pkg-a/Cargo.toml");
    let b = declaration(&parsed, "local-b", "normal", "serde");
    assert_eq!(b["manifest_path"], "crates/local-b/Cargo.toml");
}

#[test]
fn query_deps_name_miss_is_machine_readable_success() {
    let (_temp, graph) = fixture_graph();
    let parsed = run_query_deps(&graph, &["--name", "left-pad"]);

    assert_eq!(parsed["ok"], true, "a miss is an answer, not an error");
    assert_eq!(parsed["count"], 0);
    assert!(
        parsed["declarations"].as_array().expect("array").is_empty(),
        "only matching declarations are returned"
    );
    let codes: Vec<&str> = parsed["diagnostics"]
        .as_array()
        .expect("diagnostics")
        .iter()
        .filter_map(|d| d["code"].as_str())
        .collect();
    assert!(
        codes.contains(&"no_match_for_name"),
        "miss carries a stable diagnostic code, got {codes:?}"
    );
}

// ---------------------------------------------------------------------------
// AC6: --format text works and neither format leaks raw manifest body text
// ---------------------------------------------------------------------------

#[test]
fn query_deps_text_format_lists_facts_without_manifest_bodies() {
    let (_temp, graph) = fixture_graph();
    let output = egregore()
        .args(["query", "manifest-deps", "--graph"])
        .arg(&graph)
        .args(["--format", "text"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let text = String::from_utf8(output).expect("utf8");

    assert!(text.contains("serde"), "text output names dependencies");
    assert!(text.contains("1.0.228"), "text output carries versions");
    assert!(
        text.contains("crates/pkg-a/Cargo.toml"),
        "text cites handles"
    );
    // Raw manifest body text must never be emitted: table headers, the
    // `features` array, and the path key exist only in the manifest body.
    for leaked in ["[dependencies]", "features", "path = "] {
        assert!(
            !text.contains(leaked),
            "raw manifest body text {leaked:?} leaked into text output"
        );
    }
}

#[test]
fn query_deps_json_never_leaks_manifest_body_text() {
    let (_temp, graph) = fixture_graph();
    let output = egregore()
        .args(["query", "manifest-deps", "--graph"])
        .arg(&graph)
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let raw = String::from_utf8(output).expect("utf8");
    for leaked in ["[dependencies]", "parallel", "path = "] {
        assert!(
            !raw.contains(leaked),
            "raw manifest body text {leaked:?} leaked into JSON output"
        );
    }
}

// ---------------------------------------------------------------------------
// AC5: strictly read-only — no records, indexes, or working-tree mutation
// ---------------------------------------------------------------------------

fn tree_snapshot(root: &Path) -> BTreeMap<String, String> {
    fn walk(root: &Path, dir: &Path, out: &mut BTreeMap<String, String>) {
        for entry in fs::read_dir(dir).expect("read_dir") {
            let entry = entry.expect("dir entry");
            let path = entry.path();
            if path.is_dir() {
                walk(root, &path, out);
            } else {
                let rel = path
                    .strip_prefix(root)
                    .expect("under root")
                    .to_string_lossy()
                    .replace('\\', "/");
                let bytes = fs::read(&path).expect("file bytes");
                out.insert(rel, blake3::hash(&bytes).to_hex().to_string());
            }
        }
    }
    let mut out = BTreeMap::new();
    walk(root, root, &mut out);
    out
}

#[test]
fn scan_and_query_mutate_nothing_in_the_fixture_tree() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    let before = tree_snapshot(&repo);

    let graph = temp.path().join("graph.jsonl");
    egregore()
        .arg("scan")
        .arg(&repo)
        .arg("--out")
        .arg(&graph)
        .arg("--repo-id-override")
        .arg("deps-fixture")
        .assert()
        .success();
    let _ = run_query_deps(&graph, &[]);
    let _ = run_query_deps(&graph, &["--name", "serde"]);

    let after = tree_snapshot(&repo);
    assert_eq!(before, after, "fixture tree must be byte-identical");
}

// ---------------------------------------------------------------------------
// AC8 / success metric: byte-identical output across 5 consecutive runs
// ---------------------------------------------------------------------------

#[test]
fn query_deps_output_is_byte_identical_across_5_runs() {
    let (_temp, graph) = fixture_graph();
    let run = |extra: &[&str]| -> Vec<u8> {
        egregore()
            .args(["query", "manifest-deps", "--graph"])
            .arg(&graph)
            .args(extra)
            .assert()
            .success()
            .get_output()
            .stdout
            .clone()
    };
    let first_json = run(&[]);
    let first_text = run(&["--format", "text"]);
    for _ in 0..4 {
        assert_eq!(run(&[]), first_json, "JSON output must be byte-identical");
        assert_eq!(
            run(&["--format", "text"]),
            first_text,
            "text output must be byte-identical"
        );
    }
}

#[test]
fn scan_dependency_records_are_byte_identical_across_runs() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    let scan = || {
        scan_repository_at_with_override(&repo, FIXED_TIME, Some("deps-fixture"))
            .expect("fixture should scan")
            .to_jsonl()
            .expect("graph should serialize")
    };
    let first = scan();
    for _ in 0..4 {
        assert_eq!(scan(), first, "scan JSONL must be byte-identical");
    }
}

// ---------------------------------------------------------------------------
// AC7: the slice reuses the code-graph surface — records pass `eg validate`
// ---------------------------------------------------------------------------

#[test]
fn dependency_records_pass_referential_validation() {
    let (_temp, graph) = fixture_graph();
    egregore().arg("validate").arg(&graph).assert().success();
}

// ---------------------------------------------------------------------------
// Robustness: a malformed manifest degrades to a diagnostic, never a panic
// ---------------------------------------------------------------------------

#[test]
fn malformed_manifest_yields_diagnostic_not_failure() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    fs::write(
        repo.join("crates/pkg-a/Cargo.toml"),
        "[package\nname = broken",
    )
    .expect("break the manifest");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("deps-fixture"))
        .expect("scan must not fail on a malformed manifest")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let nodes = dependency_nodes(&graph);
    assert!(
        nodes
            .iter()
            .all(|n| n["dependency"]["declaring_package"] != "pkg-a"),
        "no facts are invented for an unparseable manifest"
    );
    // local-b still contributes its declaration.
    assert!(nodes.iter().any(|n| n["name"] == "serde"));

    let raw = fs::read_to_string(&graph).expect("graph text");
    let diagnostic = raw.lines().any(|line| {
        let record: Value = serde_json::from_str(line).expect("record JSON");
        record["kind"] == "Diagnostic" && record["repo_relative_path"] == "crates/pkg-a/Cargo.toml"
    });
    assert!(
        diagnostic,
        "the malformed manifest is reported as a Diagnostic"
    );
}

// ---------------------------------------------------------------------------
// Embedded round-trip: `eg query manifest-deps --data-dir` equals the JSONL answer
// ---------------------------------------------------------------------------

#[cfg(feature = "embedded-aletheiadb")]
#[test]
fn query_deps_round_trips_through_the_embedded_store() {
    let (temp, graph) = fixture_graph();
    let data_dir = temp.path().join("store");
    egregore()
        .arg("ingest")
        .arg(&graph)
        .args(["--adapter", "embedded", "--data-dir"])
        .arg(&data_dir)
        .assert()
        .success();

    let from_graph = run_query_deps(&graph, &[]);
    let output = egregore()
        .args(["query", "manifest-deps", "--data-dir"])
        .arg(&data_dir)
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let from_store: Value =
        serde_json::from_str(std::str::from_utf8(&output).expect("utf8").trim())
            .expect("store answer must be valid JSON");
    assert_eq!(
        from_store["declarations"], from_graph["declarations"],
        "embedded store answer must match the JSONL answer"
    );
}
