//! Integration tests for Cargo dependency-declaration extraction and
//! `eg query manifest-deps` (issue #180): every directly-declared Cargo dependency
//! becomes a deterministic, citable graph fact — name, kind, declared
//! requirement, resolved locked version, declaring package, and manifest
//! handle — derived locally and read-only, never via `cargo metadata`.

#![allow(missing_docs)]

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use aletheia_egregore::scan_repository_at_with_override;
use assert_cmd::Command;
use serde_json::Value;

const FIXED_TIME: &str = "2026-07-01T00:00:00Z";

fn egregore() -> Command {
    Command::cargo_bin("egregore").expect("binary should be built")
}

// ---------------------------------------------------------------------------
// Fixture: a two-member workspace with a committed Cargo.lock
// ---------------------------------------------------------------------------

/// Virtual workspace root: no `[package]`, no dependency tables — must
/// produce zero dependency facts and zero diagnostics.
const ROOT_MANIFEST: &str = r#"[workspace]
members = ["crates/pkg-a", "crates/local-b"]
"#;

/// First member: all three dependency tables, a path dependency without a
/// version requirement, a dependency missing from the lockfile, and a
/// dependency locked at two different versions.
const PKG_A_MANIFEST: &str = r#"[package]
name = "pkg-a"
version = "0.1.0"

[dependencies]
serde = "1.0.228"
local-b = { path = "../local-b" }
ghost = "0.9"
dupes = "1"

[dev-dependencies]
tempfile = "3"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
"#;

/// Second member: one normal dependency shared with pkg-a.
const LOCAL_B_MANIFEST: &str = r#"[package]
name = "local-b"
version = "0.1.0"

[dependencies]
serde = "1.0.228"
"#;

/// Committed lockfile: `serde`, `tempfile`, `cc`, and `local-b` resolve to a
/// single version; `dupes` is locked at two versions that both satisfy the
/// declared requirement `"1"` (ambiguous — the requirement cannot select
/// one); `ghost` is absent entirely.
const CARGO_LOCK: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "cc"
version = "1.0.100"

[[package]]
name = "dupes"
version = "1.0.0"

[[package]]
name = "dupes"
version = "1.5.0"

[[package]]
name = "local-b"
version = "0.1.0"

[[package]]
name = "pkg-a"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.228"

[[package]]
name = "tempfile"
version = "3.27.0"
"#;

fn write_fixture(dir: &Path) {
    fs::create_dir_all(dir.join("crates/pkg-a/src")).expect("pkg-a dir");
    fs::create_dir_all(dir.join("crates/local-b/src")).expect("local-b dir");
    fs::write(dir.join("Cargo.toml"), ROOT_MANIFEST).expect("root manifest");
    fs::write(dir.join("Cargo.lock"), CARGO_LOCK).expect("lockfile");
    fs::write(dir.join("crates/pkg-a/Cargo.toml"), PKG_A_MANIFEST).expect("pkg-a manifest");
    fs::write(dir.join("crates/local-b/Cargo.toml"), LOCAL_B_MANIFEST).expect("local-b manifest");
    fs::write(dir.join("crates/pkg-a/src/lib.rs"), "pub fn a() {}\n").expect("pkg-a lib");
    fs::write(dir.join("crates/local-b/src/lib.rs"), "pub fn b() {}\n").expect("local-b lib");
}

/// Scans the workspace fixture and writes the JSONL graph. Returns
/// (`TempDir`, graph path). The graph is written *outside* the fixture tree
/// so read-only assertions can hash the fixture exactly.
fn fixture_graph() -> (tempfile::TempDir, PathBuf) {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("deps-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");
    (temp, graph)
}

/// Parses every `DependencyDeclaration` node record from a graph JSONL.
fn dependency_nodes(graph: &Path) -> Vec<Value> {
    fs::read_to_string(graph)
        .expect("graph must be readable")
        .lines()
        .map(|line| serde_json::from_str::<Value>(line).expect("valid record JSON"))
        .filter(|record| record["kind"] == "DependencyDeclaration")
        .collect()
}

fn run_query_deps(graph: &Path, extra: &[&str]) -> Value {
    let output = egregore()
        .args(["query", "manifest-deps", "--graph"])
        .arg(graph)
        .args(extra)
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    serde_json::from_str(std::str::from_utf8(&output).expect("utf8").trim())
        .expect("stdout must be valid JSON")
}

fn declaration<'a>(parsed: &'a Value, package: &str, kind: &str, name: &str) -> &'a Value {
    parsed["declarations"]
        .as_array()
        .expect("declarations array")
        .iter()
        .find(|d| {
            d["declaring_package"] == package && d["dependency_kind"] == kind && d["name"] == name
        })
        .unwrap_or_else(|| panic!("missing declaration ({package}, {kind}, {name})"))
}

// ---------------------------------------------------------------------------
// AC1: one deterministic fact per (declaring package, name, kind)
// ---------------------------------------------------------------------------

#[test]
fn scan_captures_one_fact_per_declared_dependency() {
    let (_temp, graph) = fixture_graph();
    let nodes = dependency_nodes(&graph);

    let mut keys: Vec<(String, String, String)> = nodes
        .iter()
        .map(|n| {
            (
                n["dependency"]["declaring_package"]
                    .as_str()
                    .expect("declaring_package")
                    .to_owned(),
                n["dependency"]["dependency_kind"]
                    .as_str()
                    .expect("dependency_kind")
                    .to_owned(),
                n["name"].as_str().expect("name").to_owned(),
            )
        })
        .collect();
    keys.sort();
    let expected: Vec<(String, String, String)> = [
        ("local-b", "normal", "serde"),
        ("pkg-a", "build", "cc"),
        ("pkg-a", "dev", "tempfile"),
        ("pkg-a", "normal", "dupes"),
        ("pkg-a", "normal", "ghost"),
        ("pkg-a", "normal", "local-b"),
        ("pkg-a", "normal", "serde"),
    ]
    .iter()
    .map(|(p, k, n)| ((*p).to_owned(), (*k).to_owned(), (*n).to_owned()))
    .collect();
    assert_eq!(keys, expected, "exactly one fact per declaration");
}

// ---------------------------------------------------------------------------
// AC2: each fact carries name, kind, requirement, resolved version,
//       declaring package, and the manifest handle
// ---------------------------------------------------------------------------

#[test]
fn facts_carry_requirement_resolution_and_manifest_handle() {
    let (_temp, graph) = fixture_graph();
    let nodes = dependency_nodes(&graph);

    let serde_a = nodes
        .iter()
        .find(|n| n["name"] == "serde" && n["dependency"]["declaring_package"] == "pkg-a")
        .expect("pkg-a serde fact");
    assert_eq!(serde_a["repo_relative_path"], "crates/pkg-a/Cargo.toml");
    assert_eq!(serde_a["dependency"]["dependency_kind"], "normal");
    assert_eq!(serde_a["dependency"]["declared_requirement"], "1.0.228");
    assert_eq!(serde_a["dependency"]["resolved_version"], "1.0.228");
    assert_eq!(serde_a["dependency"]["resolution"], "locked");
    assert!(
        serde_a["id"]
            .as_str()
            .expect("stable record id")
            .starts_with("codegraph:v"),
        "dependency facts carry stable codegraph record IDs"
    );

    // Inline-table declaration: requirement is the `version` key as written.
    let cc = nodes
        .iter()
        .find(|n| n["name"] == "cc")
        .expect("cc build-dependency fact");
    assert_eq!(cc["dependency"]["dependency_kind"], "build");
    assert_eq!(cc["dependency"]["declared_requirement"], "1.0");
    assert_eq!(cc["dependency"]["resolved_version"], "1.0.100");

    // Path dependency without a version key: no fabricated requirement.
    let local_b = nodes
        .iter()
        .find(|n| n["name"] == "local-b" && n["kind"] == "DependencyDeclaration")
        .expect("local-b path-dependency fact");
    assert!(
        local_b["dependency"]["declared_requirement"].is_null(),
        "path dependency without a version key must not fabricate a requirement"
    );
    assert_eq!(local_b["dependency"]["resolved_version"], "0.1.0");
    assert_eq!(local_b["dependency"]["resolution"], "locked");
}

// ---------------------------------------------------------------------------
// AC3: lockfile-miss and ambiguity markers — never a guessed version
// ---------------------------------------------------------------------------

#[test]
fn lockfile_misses_are_marked_never_fabricated() {
    let (_temp, graph) = fixture_graph();
    let nodes = dependency_nodes(&graph);

    let ghost = nodes
        .iter()
        .find(|n| n["name"] == "ghost")
        .expect("ghost fact");
    assert_eq!(ghost["dependency"]["resolution"], "not_in_lockfile");
    assert!(ghost["dependency"]["resolved_version"].is_null());

    let dupes = nodes
        .iter()
        .find(|n| n["name"] == "dupes")
        .expect("dupes fact");
    assert_eq!(dupes["dependency"]["resolution"], "ambiguous_in_lockfile");
    assert!(
        dupes["dependency"]["resolved_version"].is_null(),
        "two locked versions must never be collapsed into a guess"
    );
}

#[test]
fn absent_lockfile_marks_every_fact_unresolved() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    fs::remove_file(repo.join("Cargo.lock")).expect("drop the lockfile");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("deps-fixture"))
        .expect("fixture should scan without a lockfile")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let nodes = dependency_nodes(&graph);
    assert!(
        !nodes.is_empty(),
        "declared facts survive a missing lockfile"
    );
    for node in &nodes {
        assert_eq!(
            node["dependency"]["resolution"], "no_lockfile",
            "every fact carries the documented unresolved marker"
        );
        assert!(
            node["dependency"]["resolved_version"].is_null(),
            "no fabricated resolved version without a lockfile"
        );
    }
    // Declared requirements are still captured as written.
    let serde_fact = nodes
        .iter()
        .find(|n| n["name"] == "serde" && n["dependency"]["declaring_package"] == "pkg-a")
        .expect("serde fact");
    assert_eq!(serde_fact["dependency"]["declared_requirement"], "1.0.228");
}

// ---------------------------------------------------------------------------
// AC4: `eg query manifest-deps` lists declarations and answers a direct lookup
// ---------------------------------------------------------------------------

#[test]
fn query_deps_lists_every_declaration_with_stable_ordering() {
    let (_temp, graph) = fixture_graph();
    let parsed = run_query_deps(&graph, &[]);

    assert_eq!(parsed["ok"], true);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(declarations.len(), 7, "all seven declared dependencies");
    assert_eq!(parsed["count"], 7);

    // Deterministic ordering: manifest path, declaring package, kind
    // (normal < dev < build), then name.
    let order: Vec<(String, String, String)> = declarations
        .iter()
        .map(|d| {
            (
                d["manifest_path"]
                    .as_str()
                    .expect("manifest_path")
                    .to_owned(),
                d["dependency_kind"].as_str().expect("kind").to_owned(),
                d["name"].as_str().expect("name").to_owned(),
            )
        })
        .collect();
    let expected: Vec<(String, String, String)> = [
        ("crates/local-b/Cargo.toml", "normal", "serde"),
        ("crates/pkg-a/Cargo.toml", "normal", "dupes"),
        ("crates/pkg-a/Cargo.toml", "normal", "ghost"),
        ("crates/pkg-a/Cargo.toml", "normal", "local-b"),
        ("crates/pkg-a/Cargo.toml", "normal", "serde"),
        ("crates/pkg-a/Cargo.toml", "dev", "tempfile"),
        ("crates/pkg-a/Cargo.toml", "build", "cc"),
    ]
    .iter()
    .map(|(m, k, n)| ((*m).to_owned(), (*k).to_owned(), (*n).to_owned()))
    .collect();
    assert_eq!(order, expected, "stable documented ordering");

    // Every row is a citable fact.
    for d in declarations {
        assert!(d["record_id"].as_str().is_some(), "row needs record_id");
        assert!(d["manifest_path"].as_str().is_some(), "row needs handle");
        assert!(d["declaring_package"].as_str().is_some());
        assert!(d["resolution"].as_str().is_some());
    }
}

#[test]
fn query_deps_answers_a_direct_name_lookup() {
    let (_temp, graph) = fixture_graph();
    let parsed = run_query_deps(&graph, &["--name", "serde"]);

    assert_eq!(parsed["ok"], true);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(
        declarations.len(),
        2,
        "serde is declared by both member crates"
    );
    for d in declarations {
        assert_eq!(d["name"], "serde");
        assert_eq!(d["resolved_version"], "1.0.228");
    }
    let a = declaration(&parsed, "pkg-a", "normal", "serde");
    assert_eq!(a["manifest_path"], "crates/pkg-a/Cargo.toml");
    let b = declaration(&parsed, "local-b", "normal", "serde");
    assert_eq!(b["manifest_path"], "crates/local-b/Cargo.toml");
}

#[test]
fn query_deps_name_miss_is_machine_readable_success() {
    let (_temp, graph) = fixture_graph();
    let parsed = run_query_deps(&graph, &["--name", "left-pad"]);

    assert_eq!(parsed["ok"], true, "a miss is an answer, not an error");
    assert_eq!(parsed["count"], 0);
    assert!(
        parsed["declarations"].as_array().expect("array").is_empty(),
        "only matching declarations are returned"
    );
    let codes: Vec<&str> = parsed["diagnostics"]
        .as_array()
        .expect("diagnostics")
        .iter()
        .filter_map(|d| d["code"].as_str())
        .collect();
    assert!(
        codes.contains(&"no_match_for_name"),
        "miss carries a stable diagnostic code, got {codes:?}"
    );
}

// ---------------------------------------------------------------------------
// AC6: --format text works and neither format leaks raw manifest body text
// ---------------------------------------------------------------------------

#[test]
fn query_deps_text_format_lists_facts_without_manifest_bodies() {
    let (_temp, graph) = fixture_graph();
    let output = egregore()
        .args(["query", "manifest-deps", "--graph"])
        .arg(&graph)
        .args(["--format", "text"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let text = String::from_utf8(output).expect("utf8");

    assert!(text.contains("serde"), "text output names dependencies");
    assert!(text.contains("1.0.228"), "text output carries versions");
    assert!(
        text.contains("crates/pkg-a/Cargo.toml"),
        "text cites handles"
    );
    // Raw manifest body text must never be emitted: table headers, the
    // `features` array, and the path key exist only in the manifest body.
    for leaked in ["[dependencies]", "features", "path = "] {
        assert!(
            !text.contains(leaked),
            "raw manifest body text {leaked:?} leaked into text output"
        );
    }
}

#[test]
fn query_deps_json_never_leaks_manifest_body_text() {
    let (_temp, graph) = fixture_graph();
    let output = egregore()
        .args(["query", "manifest-deps", "--graph"])
        .arg(&graph)
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let raw = String::from_utf8(output).expect("utf8");
    for leaked in ["[dependencies]", "parallel", "path = "] {
        assert!(
            !raw.contains(leaked),
            "raw manifest body text {leaked:?} leaked into JSON output"
        );
    }
}

// ---------------------------------------------------------------------------
// AC5: strictly read-only — no records, indexes, or working-tree mutation
// ---------------------------------------------------------------------------

fn tree_snapshot(root: &Path) -> BTreeMap<String, String> {
    fn walk(root: &Path, dir: &Path, out: &mut BTreeMap<String, String>) {
        for entry in fs::read_dir(dir).expect("read_dir") {
            let entry = entry.expect("dir entry");
            let path = entry.path();
            if path.is_dir() {
                walk(root, &path, out);
            } else {
                let rel = path
                    .strip_prefix(root)
                    .expect("under root")
                    .to_string_lossy()
                    .replace('\\', "/");
                let bytes = fs::read(&path).expect("file bytes");
                out.insert(rel, blake3::hash(&bytes).to_hex().to_string());
            }
        }
    }
    let mut out = BTreeMap::new();
    walk(root, root, &mut out);
    out
}

#[test]
fn scan_and_query_mutate_nothing_in_the_fixture_tree() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    let before = tree_snapshot(&repo);

    let graph = temp.path().join("graph.jsonl");
    egregore()
        .arg("scan")
        .arg(&repo)
        .arg("--out")
        .arg(&graph)
        .arg("--repo-id-override")
        .arg("deps-fixture")
        .assert()
        .success();
    let _ = run_query_deps(&graph, &[]);
    let _ = run_query_deps(&graph, &["--name", "serde"]);

    let after = tree_snapshot(&repo);
    assert_eq!(before, after, "fixture tree must be byte-identical");
}

// ---------------------------------------------------------------------------
// AC8 / success metric: byte-identical output across 5 consecutive runs
// ---------------------------------------------------------------------------

#[test]
fn query_deps_output_is_byte_identical_across_5_runs() {
    let (_temp, graph) = fixture_graph();
    let run = |extra: &[&str]| -> Vec<u8> {
        egregore()
            .args(["query", "manifest-deps", "--graph"])
            .arg(&graph)
            .args(extra)
            .assert()
            .success()
            .get_output()
            .stdout
            .clone()
    };
    let first_json = run(&[]);
    let first_text = run(&["--format", "text"]);
    for _ in 0..4 {
        assert_eq!(run(&[]), first_json, "JSON output must be byte-identical");
        assert_eq!(
            run(&["--format", "text"]),
            first_text,
            "text output must be byte-identical"
        );
    }
}

#[test]
fn scan_dependency_records_are_byte_identical_across_runs() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    let scan = || {
        scan_repository_at_with_override(&repo, FIXED_TIME, Some("deps-fixture"))
            .expect("fixture should scan")
            .to_jsonl()
            .expect("graph should serialize")
    };
    let first = scan();
    for _ in 0..4 {
        assert_eq!(scan(), first, "scan JSONL must be byte-identical");
    }
}

// ---------------------------------------------------------------------------
// AC7: the slice reuses the code-graph surface — records pass `eg validate`
// ---------------------------------------------------------------------------

#[test]
fn dependency_records_pass_referential_validation() {
    let (_temp, graph) = fixture_graph();
    egregore().arg("validate").arg(&graph).assert().success();
}

// ---------------------------------------------------------------------------
// PR #314 review: a workspace member always resolves through the root
// lockfile; the authoritative lockfile's corruption is never skipped
// ---------------------------------------------------------------------------

/// Cargo resolves a workspace member through the workspace ROOT's lockfile
/// even when a stale or corrupt local `Cargo.lock` sits beside the member's
/// manifest — the member-local file is dead state Cargo never reads. Only
/// standalone packages and workspace roots own their own-directory lockfile.
#[test]
fn member_local_lockfiles_are_ignored_in_favor_of_the_workspace_root() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    // A corrupt local lockfile beside member pkg-a, and a stale local
    // lockfile beside member local-b (serde locked at a version the root
    // lockfile does not hold). Cargo reads neither.
    fs::write(repo.join("crates/pkg-a/Cargo.lock"), "not [ valid toml")
        .expect("corrupt nested lockfile");
    fs::write(
        repo.join("crates/local-b/Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.100\"\n",
    )
    .expect("stale nested lockfile");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("deps-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let nodes = dependency_nodes(&graph);
    let serde_a = nodes
        .iter()
        .find(|n| n["dependency"]["declaring_package"] == "pkg-a" && n["name"] == "serde")
        .expect("pkg-a serde fact");
    assert_eq!(
        serde_a["dependency"]["resolution"], "locked",
        "a member with a corrupt local lockfile still resolves from the workspace root"
    );
    assert_eq!(serde_a["dependency"]["resolved_version"], "1.0.228");
    let serde_b = nodes
        .iter()
        .find(|n| n["dependency"]["declaring_package"] == "local-b" && n["name"] == "serde")
        .expect("local-b serde fact");
    assert_eq!(
        serde_b["dependency"]["resolution"], "locked",
        "a member with a stale local lockfile resolves from the root, never the local file"
    );
    assert_eq!(
        serde_b["dependency"]["resolved_version"], "1.0.228",
        "the stale member-local version must never surface"
    );
}

/// For a standalone package (no owning workspace) the own-directory lockfile
/// IS the authority: when it exists but cannot be parsed the dependencies are
/// `lockfile_unreadable` — never a guess, never an unrelated ancestor.
#[test]
fn standalone_corrupt_lockfile_marks_facts_lockfile_unreadable() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("src")).expect("src dir");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"loner\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("manifest");
    fs::write(repo.join("Cargo.lock"), "not [ valid toml").expect("corrupt lockfile");
    fs::write(repo.join("src/lib.rs"), "pub fn f() {}\n").expect("lib.rs");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("loner-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let row = &parsed["declarations"].as_array().expect("declarations")[0];
    assert_eq!(row["resolution"], "lockfile_unreadable");
    assert!(row["resolved_version"].is_null());
}

// ---------------------------------------------------------------------------
// Robustness: a malformed manifest degrades to a diagnostic, never a panic
// ---------------------------------------------------------------------------

#[test]
fn malformed_manifest_yields_diagnostic_not_failure() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(&repo).expect("repo dir");
    write_fixture(&repo);
    fs::write(
        repo.join("crates/pkg-a/Cargo.toml"),
        "[package\nname = broken",
    )
    .expect("break the manifest");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("deps-fixture"))
        .expect("scan must not fail on a malformed manifest")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let nodes = dependency_nodes(&graph);
    assert!(
        nodes
            .iter()
            .all(|n| n["dependency"]["declaring_package"] != "pkg-a"),
        "no facts are invented for an unparseable manifest"
    );
    // local-b still contributes its declaration.
    assert!(nodes.iter().any(|n| n["name"] == "serde"));

    let raw = fs::read_to_string(&graph).expect("graph text");
    let diagnostic = raw.lines().any(|line| {
        let record: Value = serde_json::from_str(line).expect("record JSON");
        record["kind"] == "Diagnostic" && record["repo_relative_path"] == "crates/pkg-a/Cargo.toml"
    });
    assert!(
        diagnostic,
        "the malformed manifest is reported as a Diagnostic"
    );
}

// ---------------------------------------------------------------------------
// Embedded round-trip: `eg query manifest-deps --data-dir` equals the JSONL answer
// ---------------------------------------------------------------------------

#[cfg(feature = "embedded-aletheiadb")]
#[test]
fn query_deps_round_trips_through_the_embedded_store() {
    let (temp, graph) = fixture_graph();
    let data_dir = temp.path().join("store");
    egregore()
        .arg("ingest")
        .arg(&graph)
        .args(["--adapter", "embedded", "--data-dir"])
        .arg(&data_dir)
        .assert()
        .success();

    let from_graph = run_query_deps(&graph, &[]);
    let output = egregore()
        .args(["query", "manifest-deps", "--data-dir"])
        .arg(&data_dir)
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let from_store: Value =
        serde_json::from_str(std::str::from_utf8(&output).expect("utf8").trim())
            .expect("store answer must be valid JSON");
    assert_eq!(
        from_store["declarations"], from_graph["declarations"],
        "embedded store answer must match the JSONL answer"
    );
}

/// Sorted `(relative path, bytes)` fingerprint of every file under `root`
/// (mirrors `tests/integration/asof_file_symbols.rs`).
#[cfg(feature = "embedded-aletheiadb")]
fn dir_fingerprint(root: &Path) -> Vec<(String, Vec<u8>)> {
    fn walk(dir: &Path, base: &Path, out: &mut Vec<(String, Vec<u8>)>) {
        let mut entries: Vec<_> = fs::read_dir(dir).unwrap().map(|e| e.unwrap()).collect();
        entries.sort_by_key(std::fs::DirEntry::path);
        for entry in entries {
            let ft = entry.file_type().unwrap();
            let path = entry.path();
            if ft.is_dir() {
                walk(&path, base, out);
            } else if ft.is_file() {
                let rel = path
                    .strip_prefix(base)
                    .unwrap()
                    .to_string_lossy()
                    .into_owned();
                out.push((rel, fs::read(&path).unwrap()));
            }
        }
    }
    let mut out = Vec::new();
    walk(root, root, &mut out);
    out
}

/// PR #314 review: the store-backed query is strictly read-only. Opening the
/// embedded engine in place re-persists its on-disk index files, so
/// `--data-dir` must read from a throwaway copy and leave the live store
/// byte-for-byte untouched (same contract as the other read-only lanes).
#[cfg(feature = "embedded-aletheiadb")]
#[test]
fn query_manifest_deps_data_dir_is_strictly_read_only() {
    let (temp, graph) = fixture_graph();
    let data_dir = temp.path().join("store");
    egregore()
        .arg("ingest")
        .arg(&graph)
        .args(["--adapter", "embedded", "--data-dir"])
        .arg(&data_dir)
        .assert()
        .success();

    let before = dir_fingerprint(&data_dir);
    egregore()
        .args(["query", "manifest-deps", "--data-dir"])
        .arg(&data_dir)
        .assert()
        .success();
    let after = dir_fingerprint(&data_dir);
    assert_eq!(
        before, after,
        "query manifest-deps must not modify any store file when reading --data-dir"
    );
}

// ---------------------------------------------------------------------------
// PR #314 review: dependency facts must be attributable to their repository
// ---------------------------------------------------------------------------

/// Scans two distinct repositories that both declare `serde` (at different
/// locked versions) and merges the scans into one multi-repo graph.
/// Returns `(tempdir, merged graph path)`.
fn two_repo_graph() -> (tempfile::TempDir, PathBuf) {
    let temp = tempfile::tempdir().expect("temp dir");
    for (dir, req, locked) in [("repo-a", "1.0.228", "1.0.228"), ("repo-b", "1", "1.0.100")] {
        let root = temp.path().join(dir);
        fs::create_dir_all(root.join("src")).expect("src dir");
        fs::write(
            root.join("Cargo.toml"),
            format!("[package]\nname = \"{dir}-pkg\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"{req}\"\n"),
        )
        .expect("manifest");
        fs::write(
            root.join("Cargo.lock"),
            format!("version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"{locked}\"\n"),
        )
        .expect("lockfile");
        fs::write(root.join("src/lib.rs"), "pub fn f() {}\n").expect("lib.rs");
    }
    let mut merged = String::new();
    for dir in ["repo-a", "repo-b"] {
        merged.push_str(
            &scan_repository_at_with_override(temp.path().join(dir), FIXED_TIME, Some(dir))
                .expect("fixture should scan")
                .to_jsonl()
                .expect("graph should serialize"),
        );
    }
    let graph = temp.path().join("merged.jsonl");
    fs::write(&graph, merged).expect("write merged graph");
    (temp, graph)
}

#[test]
fn multi_repo_rows_carry_distinct_repository_labels() {
    let (_temp, graph) = two_repo_graph();
    let parsed = run_query_deps(&graph, &["--name", "serde"]);

    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(declarations.len(), 2, "both repos declare serde");
    let mut labels: Vec<&str> = declarations
        .iter()
        .map(|d| {
            d["repository"]
                .as_str()
                .expect("every row must carry its owning repository label")
        })
        .collect();
    labels.sort_unstable();
    assert_eq!(
        labels,
        vec!["repo-a", "repo-b"],
        "rows from unrelated repos must be distinguishable"
    );
    // The two rows are not otherwise mergeable: resolved versions differ.
    let by_repo = |label: &str| {
        declarations
            .iter()
            .find(|d| d["repository"] == label)
            .unwrap_or_else(|| panic!("row for {label}"))
    };
    assert_eq!(by_repo("repo-a")["resolved_version"], "1.0.228");
    assert_eq!(by_repo("repo-b")["resolved_version"], "1.0.100");
}

#[test]
fn repo_selector_scopes_manifest_deps_to_one_repository() {
    let (_temp, graph) = two_repo_graph();
    let parsed = run_query_deps(&graph, &["--name", "serde", "--repo", "repo-a"]);

    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(declarations.len(), 1, "scoped to exactly one repository");
    assert_eq!(declarations[0]["repository"], "repo-a");
    assert_eq!(declarations[0]["resolved_version"], "1.0.228");
}

#[test]
fn unknown_repo_selector_is_rejected_machine_readably() {
    let (_temp, graph) = two_repo_graph();
    let output = egregore()
        .args(["query", "manifest-deps", "--graph"])
        .arg(&graph)
        .args(["--repo", "does-not-exist"])
        .assert()
        .failure()
        .get_output()
        .stderr
        .clone();
    let diag: Value = String::from_utf8_lossy(&output)
        .lines()
        .find_map(|l| serde_json::from_str(l.trim()).ok())
        .expect("stderr should carry a machine-readable diagnostic");
    assert_eq!(diag["code"], "unknown_repository_selector");
}

/// The topology that makes attribution possible must itself be valid: the
/// manifest `File` node and its `CONTAINS` chain pass `eg validate`.
#[test]
fn dependency_topology_passes_referential_validation() {
    let (_temp, graph) = two_repo_graph();
    egregore().arg("validate").arg(&graph).assert().success();
}

/// Repository —CONTAINS→ File(Cargo.toml) —CONTAINS→ `DependencyDeclaration`:
/// the exact chain `RepositoryIndex` walks for ownership.
#[test]
fn dependency_facts_are_edge_attached_to_the_manifest_file() {
    let (_temp, graph) = fixture_graph();
    let records: Vec<Value> = fs::read_to_string(&graph)
        .expect("graph readable")
        .lines()
        .map(|l| serde_json::from_str(l).expect("record JSON"))
        .collect();

    let dep = records
        .iter()
        .find(|r| {
            r["kind"] == "DependencyDeclaration"
                && r["name"] == "serde"
                && r["repo_relative_path"] == "crates/pkg-a/Cargo.toml"
        })
        .expect("serde dependency node");
    let manifest_file = records
        .iter()
        .find(|r| r["kind"] == "File" && r["repo_relative_path"] == "crates/pkg-a/Cargo.toml")
        .expect("the owning Cargo.toml gets a File node");
    // File —CONTAINS→ DependencyDeclaration
    assert!(
        records.iter().any(|r| r["record_type"] == "edge"
            && r["label"] == "CONTAINS"
            && r["source"] == manifest_file["id"]
            && r["target"] == dep["id"]),
        "manifest file must contain the dependency fact"
    );
    // Repository —CONTAINS→ File
    let repo = records
        .iter()
        .find(|r| r["kind"] == "Repository")
        .expect("repository node");
    assert!(
        records.iter().any(|r| r["record_type"] == "edge"
            && r["label"] == "CONTAINS"
            && r["source"] == repo["id"]
            && r["target"] == manifest_file["id"]),
        "repository must contain the manifest file"
    );
    // The manifest File node never embeds raw manifest body text.
    let summary = manifest_file["summary"].as_str().expect("summary");
    assert!(
        !summary.contains("[dependencies]") && !summary.contains("1.0.228"),
        "manifest File summary must not embed manifest body text, got {summary:?}"
    );
}

// ---------------------------------------------------------------------------
// PR #314 review: `package = "…"` rename pairs are never collapsed
// ---------------------------------------------------------------------------

/// A manifest depending on two versions of the same crate via Cargo's rename
/// syntax. Both entries must survive as distinct facts, each resolved against
/// its own declared requirement.
fn rename_pair_graph() -> (tempfile::TempDir, PathBuf) {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("src")).expect("src dir");
    fs::write(
        repo.join("Cargo.toml"),
        r#"[package]
name = "hal-user"
version = "0.1.0"

[dependencies]
embedded-hal = "0.2"
embedded-hal-1 = { package = "embedded-hal", version = "1" }
"#,
    )
    .expect("manifest");
    fs::write(
        repo.join("Cargo.lock"),
        r#"version = 4

[[package]]
name = "embedded-hal"
version = "0.2.7"

[[package]]
name = "embedded-hal"
version = "1.0.0"
"#,
    )
    .expect("lockfile");
    fs::write(repo.join("src/lib.rs"), "pub fn f() {}\n").expect("lib.rs");
    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("rename-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");
    (temp, graph)
}

#[test]
fn rename_pair_yields_two_rows_resolved_per_requirement() {
    let (_temp, graph) = rename_pair_graph();
    let parsed = run_query_deps(&graph, &["--name", "embedded-hal"]);

    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(
        declarations.len(),
        2,
        "both declared entries survive; --name matches the real crate name"
    );
    let plain = &declarations[0];
    assert_eq!(plain["name"], "embedded-hal");
    assert!(plain["declared_as"].is_null(), "plain entry has no alias");
    assert_eq!(plain["declared_requirement"], "0.2");
    assert_eq!(plain["resolved_version"], "0.2.7");
    assert_eq!(plain["resolution"], "locked");

    let renamed = &declarations[1];
    assert_eq!(renamed["name"], "embedded-hal");
    assert_eq!(renamed["declared_as"], "embedded-hal-1");
    assert_eq!(renamed["declared_requirement"], "1");
    assert_eq!(renamed["resolved_version"], "1.0.0");
    assert_eq!(renamed["resolution"], "locked");

    assert_ne!(
        plain["record_id"], renamed["record_id"],
        "each declared entry carries its own stable identity"
    );

    // The topology and identities stay referentially valid.
    egregore().arg("validate").arg(&graph).assert().success();
}

#[cfg(feature = "embedded-aletheiadb")]
#[test]
fn rename_pair_round_trips_through_the_embedded_store() {
    let (temp, graph) = rename_pair_graph();
    let data_dir = temp.path().join("store");
    egregore()
        .arg("ingest")
        .arg(&graph)
        .args(["--adapter", "embedded", "--data-dir"])
        .arg(&data_dir)
        .assert()
        .success();

    let from_graph = run_query_deps(&graph, &[]);
    let output = egregore()
        .args(["query", "manifest-deps", "--data-dir"])
        .arg(&data_dir)
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let from_store: Value =
        serde_json::from_str(std::str::from_utf8(&output).expect("utf8").trim())
            .expect("store answer must be valid JSON");
    assert_eq!(
        from_store["declarations"], from_graph["declarations"],
        "declared_as and per-alias resolution must survive the embedded store"
    );
}

// ---------------------------------------------------------------------------
// PR #314 review: a stale lockfile's sole version never masquerades as locked
// ---------------------------------------------------------------------------

/// A stale (or shared) lockfile can hold exactly one version of a crate that
/// does not satisfy the declaration being scanned; the mismatch must surface
/// as `requirement_unsatisfied_in_lockfile` with no resolved version — the
/// stale version is a fabrication, not a resolution.
#[test]
fn stale_lockfile_sole_version_marks_requirement_unsatisfied() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("src")).expect("src dir");
    fs::write(
        repo.join("Cargo.toml"),
        r#"[package]
name = "stale-user"
version = "0.1.0"

[dependencies]
foo = "2"
bar = "1"
"#,
    )
    .expect("manifest");
    // The lockfile is stale: `foo` is still locked at 1.0.0 (fails `"2"`),
    // while `bar` is locked at a satisfying 1.4.2.
    fs::write(
        repo.join("Cargo.lock"),
        r#"version = 4

[[package]]
name = "bar"
version = "1.4.2"

[[package]]
name = "foo"
version = "1.0.0"
"#,
    )
    .expect("lockfile");
    fs::write(repo.join("src/lib.rs"), "pub fn f() {}\n").expect("lib.rs");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("stale-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &[]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(declarations.len(), 2);

    let foo = declarations
        .iter()
        .find(|d| d["name"] == "foo")
        .expect("foo row");
    assert_eq!(
        foo["resolution"], "requirement_unsatisfied_in_lockfile",
        "the stale sole locked version fails the declared requirement"
    );
    assert!(
        foo["resolved_version"].is_null(),
        "the mismatched stale version is never presented as resolved"
    );
    assert_eq!(foo["declared_requirement"], "2");

    // A satisfying sole locked version still resolves.
    let bar = declarations
        .iter()
        .find(|d| d["name"] == "bar")
        .expect("bar row");
    assert_eq!(bar["resolution"], "locked");
    assert_eq!(bar["resolved_version"], "1.4.2");
}

// ---------------------------------------------------------------------------
// PR #314 review: a miss is never definitive while manifests were skipped
// ---------------------------------------------------------------------------

/// Repo with one malformed manifest and one valid one: every answer — hit,
/// miss, and full listing — must carry a `skipped_manifest` diagnostic citing
/// the skipped manifest's repo-relative handle, so "do we depend on X?" is
/// never answered definitively while coverage has holes.
fn partially_unparseable_graph() -> (tempfile::TempDir, PathBuf) {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("crates/good/src")).expect("good dir");
    fs::create_dir_all(repo.join("crates/broken")).expect("broken dir");
    fs::write(
        repo.join("crates/good/Cargo.toml"),
        "[package]\nname = \"good\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("good manifest");
    fs::write(repo.join("crates/broken/Cargo.toml"), "[package\nbroken =")
        .expect("broken manifest");
    fs::write(repo.join("crates/good/src/lib.rs"), "pub fn g() {}\n").expect("lib.rs");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("skipped-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");
    (temp, graph)
}

fn skipped_diagnostics(parsed: &Value) -> Vec<&Value> {
    parsed["diagnostics"]
        .as_array()
        .expect("diagnostics")
        .iter()
        .filter(|d| d["code"] == "skipped_manifest")
        .collect()
}

#[test]
fn name_miss_with_skipped_manifest_is_visibly_non_definitive() {
    let (_temp, graph) = partially_unparseable_graph();
    let parsed = run_query_deps(&graph, &["--name", "left-pad"]);

    assert_eq!(parsed["ok"], true, "still a machine-readable success");
    assert_eq!(parsed["count"], 0);
    let codes: Vec<&str> = parsed["diagnostics"]
        .as_array()
        .expect("diagnostics")
        .iter()
        .filter_map(|d| d["code"].as_str())
        .collect();
    assert!(
        codes.contains(&"no_match_for_name"),
        "the miss diagnostic stays, got {codes:?}"
    );
    let skipped = skipped_diagnostics(&parsed);
    assert_eq!(skipped.len(), 1, "the skipped manifest is surfaced");
    assert_eq!(
        skipped[0]["detail"], "crates/broken/Cargo.toml",
        "the diagnostic cites the skipped manifest's repo-relative handle"
    );
    assert!(
        skipped[0]["record_id"]
            .as_str()
            .is_some_and(|id| id.starts_with("codegraph:v")),
        "the diagnostic cites the Diagnostic record ID"
    );
}

#[test]
fn name_hit_and_full_listing_also_carry_skipped_manifest_diagnostics() {
    let (_temp, graph) = partially_unparseable_graph();

    let hit = run_query_deps(&graph, &["--name", "serde"]);
    assert_eq!(hit["count"], 1, "the valid manifest's row is returned");
    assert_eq!(
        skipped_diagnostics(&hit).len(),
        1,
        "a hit is honestly qualified too"
    );

    let full = run_query_deps(&graph, &[]);
    assert_eq!(full["count"], 1);
    assert_eq!(skipped_diagnostics(&full).len(), 1);
}

#[test]
fn clean_repo_carries_no_skipped_manifest_diagnostics() {
    let (_temp, graph) = fixture_graph();
    for extra in [
        &[][..],
        &["--name", "serde"][..],
        &["--name", "left-pad"][..],
    ] {
        let parsed = run_query_deps(&graph, extra);
        assert!(
            skipped_diagnostics(&parsed).is_empty(),
            "a fully-parsed tree must not report skipped manifests"
        );
    }
}

// ---------------------------------------------------------------------------
// PR #314 review: the lockfile walk respects workspace/package boundaries
// ---------------------------------------------------------------------------

/// Workspace root (`members = ["crates/*"]`, `exclude = ["crates/excluded"]`)
/// with a root lockfile, plus a genuine member, an excluded member, and an
/// independent nested crate outside the members globs. Only the genuine
/// member may resolve from the root lockfile; Cargo would give the others
/// their own (missing) lockfile, so fabricating `locked` from the unrelated
/// ancestor is forbidden.
fn workspace_boundary_graph() -> (tempfile::TempDir, PathBuf) {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    for dir in [
        "crates/member/src",
        "crates/excluded/src",
        "vendor/independent/src",
    ] {
        fs::create_dir_all(repo.join(dir)).expect("dirs");
    }
    fs::write(
        repo.join("Cargo.toml"),
        r#"[workspace]
members = ["crates/*"]
exclude = ["crates/excluded"]
"#,
    )
    .expect("workspace manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    for (dir, pkg) in [
        ("crates/member", "member"),
        ("crates/excluded", "excluded"),
        ("vendor/independent", "independent"),
    ] {
        fs::write(
            repo.join(dir).join("Cargo.toml"),
            format!("[package]\nname = \"{pkg}\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n"),
        )
        .expect("member manifest");
        fs::write(repo.join(dir).join("src/lib.rs"), "pub fn f() {}\n").expect("lib.rs");
    }

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("boundary-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");
    (temp, graph)
}

#[test]
fn ancestor_lockfile_only_resolves_genuine_workspace_members() {
    let (_temp, graph) = workspace_boundary_graph();
    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(declarations.len(), 3, "all three crates declare serde");

    let by_pkg = |pkg: &str| {
        declarations
            .iter()
            .find(|d| d["declaring_package"] == pkg)
            .unwrap_or_else(|| panic!("row for {pkg}"))
    };

    // Genuine glob-matched member: covered by the root workspace lockfile.
    let member = by_pkg("member");
    assert_eq!(member["resolution"], "locked");
    assert_eq!(member["resolved_version"], "1.0.228");

    // Excluded member: Cargo treats it as standalone — its own (missing)
    // lockfile, never the ancestor's.
    let excluded = by_pkg("excluded");
    assert_eq!(
        excluded["resolution"], "no_lockfile",
        "an excluded crate must not resolve from the workspace lockfile"
    );
    assert!(excluded["resolved_version"].is_null());

    // Independent nested crate outside the members globs: same.
    let independent = by_pkg("independent");
    assert_eq!(
        independent["resolution"], "no_lockfile",
        "an independent nested crate must not resolve from an unrelated ancestor lockfile"
    );
    assert!(independent["resolved_version"].is_null());
}

// ---------------------------------------------------------------------------
// PR #314 review: a [workspace]-declaring manifest is a root, lockfile or not
// ---------------------------------------------------------------------------

/// A nested directory whose `Cargo.toml` declares `[workspace]` is a
/// workspace ROOT: Cargo would create/use the lockfile there, never an outer
/// one — even when an outer workspace's member globs would match. Without its
/// own lockfile the answer is `no_lockfile`, never the outer resolution.
#[test]
fn nested_workspace_root_without_lockfile_never_uses_outer_lockfile() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("crates/innerws/pkgs/leaf/src")).expect("dirs");
    fs::create_dir_all(repo.join("crates/innerws/src")).expect("dirs");
    // Outer workspace with a lockfile and a deep glob that would match.
    fs::write(
        repo.join("Cargo.toml"),
        "[workspace]\nmembers = [\"crates/**\"]\n",
    )
    .expect("outer manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("outer lockfile");
    // Inner workspace ROOT (package + [workspace]), no lockfile of its own.
    fs::write(
        repo.join("crates/innerws/Cargo.toml"),
        "[package]\nname = \"innerws\"\nversion = \"0.1.0\"\n\n[workspace]\nmembers = [\"pkgs/*\"]\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("inner root manifest");
    fs::write(repo.join("crates/innerws/src/lib.rs"), "pub fn i() {}\n").expect("lib");
    // A member of the INNER workspace.
    fs::write(
        repo.join("crates/innerws/pkgs/leaf/Cargo.toml"),
        "[package]\nname = \"leaf\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("leaf manifest");
    fs::write(
        repo.join("crates/innerws/pkgs/leaf/src/lib.rs"),
        "pub fn l() {}\n",
    )
    .expect("lib");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("innerws-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(declarations.len(), 2);
    for declaration in declarations {
        assert_eq!(
            declaration["resolution"], "no_lockfile",
            "{}: the inner workspace root has no lockfile; the outer one is never consulted",
            declaration["declaring_package"]
        );
        assert!(declaration["resolved_version"].is_null());
    }
}

// ---------------------------------------------------------------------------
// PR #314 review: in-tree path dependencies join the workspace automatically
// ---------------------------------------------------------------------------

/// Cargo treats a workspace-root package's in-tree `path = "…"` dependencies
/// (transitively) as workspace members even when `members` does not list
/// them; they resolve from the root lockfile.
#[test]
fn path_dependencies_join_the_workspace_for_lockfile_resolution() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("crates/helper/sub/src")).expect("dirs");
    fs::create_dir_all(repo.join("crates/helper/src")).expect("dirs");
    fs::create_dir_all(repo.join("src")).expect("dirs");
    // Root package + empty [workspace]: helper is a member only via the
    // path dependency; sub joins transitively through helper.
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"root-pkg\"\nversion = \"0.1.0\"\n\n[workspace]\n\n[dependencies]\nhelper = { path = \"crates/helper\" }\nserde = \"1\"\n",
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    fs::write(repo.join("src/lib.rs"), "pub fn r() {}\n").expect("lib");
    fs::write(
        repo.join("crates/helper/Cargo.toml"),
        "[package]\nname = \"helper\"\nversion = \"0.1.0\"\n\n[dependencies]\nsub = { path = \"sub\" }\nserde = \"1\"\n",
    )
    .expect("helper manifest");
    fs::write(repo.join("crates/helper/src/lib.rs"), "pub fn h() {}\n").expect("lib");
    fs::write(
        repo.join("crates/helper/sub/Cargo.toml"),
        "[package]\nname = \"sub\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("sub manifest");
    fs::write(repo.join("crates/helper/sub/src/lib.rs"), "pub fn s() {}\n").expect("lib");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("pathdep-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    assert_eq!(
        declarations.len(),
        3,
        "root, helper, and sub all declare serde"
    );
    for declaration in declarations {
        assert_eq!(
            declaration["resolution"], "locked",
            "{}: path-dependency members resolve from the root lockfile",
            declaration["declaring_package"]
        );
        assert_eq!(declaration["resolved_version"], "1.0.228");
    }
}

// ---------------------------------------------------------------------------
// PR #314 review: --repo scoping applies to skipped-manifest diagnostics
// ---------------------------------------------------------------------------

/// Two merged repos where only repo B has a malformed manifest: a query
/// scoped to repo A must not be qualified by B's coverage hole, a query
/// scoped to B must be, and an unscoped query reports it (with its owning
/// repository label).
fn two_repo_one_broken_graph() -> (tempfile::TempDir, PathBuf) {
    let temp = tempfile::tempdir().expect("temp dir");
    for (dir, broken) in [("repo-a", false), ("repo-b", true)] {
        let root = temp.path().join(dir);
        fs::create_dir_all(root.join("src")).expect("dirs");
        fs::write(
            root.join("Cargo.toml"),
            format!("[package]\nname = \"{dir}-pkg\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n"),
        )
        .expect("manifest");
        fs::write(root.join("src/lib.rs"), "pub fn f() {}\n").expect("lib");
        if broken {
            fs::create_dir_all(root.join("crates/broken")).expect("dirs");
            fs::write(root.join("crates/broken/Cargo.toml"), "[package\nbroken =")
                .expect("broken manifest");
        }
    }
    let mut merged = String::new();
    for dir in ["repo-a", "repo-b"] {
        merged.push_str(
            &scan_repository_at_with_override(temp.path().join(dir), FIXED_TIME, Some(dir))
                .expect("fixture should scan")
                .to_jsonl()
                .expect("graph should serialize"),
        );
    }
    let graph = temp.path().join("merged.jsonl");
    fs::write(&graph, merged).expect("write merged graph");
    (temp, graph)
}

#[test]
fn repo_scoped_queries_drop_foreign_skipped_manifest_diagnostics() {
    let (_temp, graph) = two_repo_one_broken_graph();

    // Scoped to the clean repo: no foreign coverage-hole qualification.
    let scoped_a = run_query_deps(&graph, &["--repo", "repo-a"]);
    assert!(
        skipped_diagnostics(&scoped_a).is_empty(),
        "repo A's answer must not be qualified by repo B's malformed manifest"
    );

    // Scoped to the broken repo: its own hole is surfaced.
    let scoped_b = run_query_deps(&graph, &["--repo", "repo-b"]);
    let b_skipped = skipped_diagnostics(&scoped_b);
    assert_eq!(b_skipped.len(), 1);
    assert_eq!(b_skipped[0]["detail"], "crates/broken/Cargo.toml");

    // Unscoped: the hole is reported and attributed.
    let unscoped = run_query_deps(&graph, &[]);
    let all_skipped = skipped_diagnostics(&unscoped);
    assert_eq!(all_skipped.len(), 1);
    assert_eq!(
        all_skipped[0]["repository"], "repo-b",
        "unscoped diagnostics carry their owning repository label"
    );
}

// ---------------------------------------------------------------------------
// PR #314 review: member manifests seed the automatic path-dep closure too
// ---------------------------------------------------------------------------

/// Cargo's automatic path-dependency membership grows from the root package
/// AND every explicit member: `crates/app` (a glob member) depending on
/// `../helper` makes helper a member even though no glob matches it — for
/// both a package root and a virtual root.
fn member_seeded_path_dep_graph(virtual_root: bool) -> (tempfile::TempDir, PathBuf) {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("crates/app/src")).expect("dirs");
    fs::create_dir_all(repo.join("crates/helper/src")).expect("dirs");
    let root_manifest = if virtual_root {
        "[workspace]\nmembers = [\"crates/app\"]\n".to_owned()
    } else {
        fs::create_dir_all(repo.join("src")).expect("dirs");
        fs::write(repo.join("src/lib.rs"), "pub fn r() {}\n").expect("lib");
        "[package]\nname = \"root-pkg\"\nversion = \"0.1.0\"\n\n[workspace]\nmembers = [\"crates/app\"]\n\n[dependencies]\nserde = \"1\"\n".to_owned()
    };
    fs::write(repo.join("Cargo.toml"), root_manifest).expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    fs::write(
        repo.join("crates/app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\n\n[dependencies]\nhelper = { path = \"../helper\" }\nserde = \"1\"\n",
    )
    .expect("app manifest");
    fs::write(repo.join("crates/app/src/lib.rs"), "pub fn a() {}\n").expect("lib");
    fs::write(
        repo.join("crates/helper/Cargo.toml"),
        "[package]\nname = \"helper\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("helper manifest");
    fs::write(repo.join("crates/helper/src/lib.rs"), "pub fn h() {}\n").expect("lib");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("memberseed-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");
    (temp, graph)
}

#[test]
fn member_path_dependencies_join_the_workspace() {
    for virtual_root in [false, true] {
        let (_temp, graph) = member_seeded_path_dep_graph(virtual_root);
        let parsed = run_query_deps(&graph, &["--name", "serde"]);
        let declarations = parsed["declarations"].as_array().expect("declarations");
        let helper = declarations
            .iter()
            .find(|d| d["declaring_package"] == "helper")
            .expect("helper row");
        assert_eq!(
            helper["resolution"], "locked",
            "virtual_root={virtual_root}: a glob member's path dependency joins the workspace"
        );
        assert_eq!(helper["resolved_version"], "1.0.228");
        let app = declarations
            .iter()
            .find(|d| d["declaring_package"] == "app")
            .expect("app row");
        assert_eq!(app["resolution"], "locked");
    }
}

// ---------------------------------------------------------------------------
// PR #314 review: absolute in-tree path dependencies are normalized
// ---------------------------------------------------------------------------

/// An absolute `path = "/…/repo/crates/helper"` pointing inside the
/// workspace root converts to the correct root-relative member path; an
/// absolute path pointing outside the tree is skipped without error.
#[test]
fn absolute_in_tree_path_dependencies_are_members() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("crates/helper/src")).expect("dirs");
    fs::create_dir_all(repo.join("src")).expect("dirs");
    // An out-of-tree absolute target (exists, but outside the repo root).
    fs::create_dir_all(temp.path().join("outside")).expect("dirs");
    fs::write(
        temp.path().join("outside/Cargo.toml"),
        "[package]\nname = \"outside\"\nversion = \"0.1.0\"\n",
    )
    .expect("outside manifest");

    let in_tree = repo.join("crates/helper");
    let out_of_tree = temp.path().join("outside");
    fs::write(
        repo.join("Cargo.toml"),
        format!(
            "[package]\nname = \"root-pkg\"\nversion = \"0.1.0\"\n\n[workspace]\n\n[dependencies]\nhelper = {{ path = \"{}\" }}\noutside = {{ path = \"{}\" }}\nserde = \"1\"\n",
            in_tree.display(),
            out_of_tree.display(),
        ),
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    fs::write(repo.join("src/lib.rs"), "pub fn r() {}\n").expect("lib");
    fs::write(
        repo.join("crates/helper/Cargo.toml"),
        "[package]\nname = \"helper\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("helper manifest");
    fs::write(repo.join("crates/helper/src/lib.rs"), "pub fn h() {}\n").expect("lib");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("abs-path-fixture"))
        .expect("scan must not fail on absolute path dependencies")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    let helper = declarations
        .iter()
        .find(|d| d["declaring_package"] == "helper")
        .expect("helper row");
    assert_eq!(
        helper["resolution"], "locked",
        "an absolute in-tree path dependency is a workspace member"
    );
    assert_eq!(helper["resolved_version"], "1.0.228");
}

/// Builds a path to `target` that is relative to the test's current working
/// directory: a direct `strip_prefix` when `target` lives under it, else a
/// lexical `..`-climb to the filesystem root. Used to invoke the scanner the
/// way `eg scan .` does — with a relative repo root.
fn relative_path_from_cwd(target: &Path) -> PathBuf {
    let cwd = std::env::current_dir().expect("cwd");
    if let Ok(stripped) = target.strip_prefix(&cwd) {
        return stripped.to_path_buf();
    }
    let mut rel = PathBuf::new();
    for component in cwd.components() {
        if matches!(component, std::path::Component::Normal(_)) {
            rel.push("..");
        }
    }
    for component in target.components() {
        if let std::path::Component::Normal(part) = component {
            rel.push(part);
        }
    }
    rel
}

/// PR #314 review: `eg scan .` passes a *relative* repo root, while an
/// in-tree `path = "…"` dependency may be declared absolute. Membership
/// normalization must absolutize the workspace root before stripping the
/// prefix; otherwise the member silently drops to `no_lockfile`.
#[test]
fn absolute_path_dependencies_resolve_under_a_relative_scan_root() {
    // The fixture lives under the crate's target tmpdir so a relative path
    // from the test's working directory (the package root) reaches it
    // without crossing filesystem roots.
    let temp = tempfile::Builder::new()
        .prefix("issue180-relative-root-")
        .tempdir_in(env!("CARGO_TARGET_TMPDIR"))
        .expect("temp dir under target");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("crates/helper/src")).expect("dirs");
    fs::create_dir_all(repo.join("src")).expect("dirs");

    let in_tree = repo.join("crates/helper");
    fs::write(
        repo.join("Cargo.toml"),
        format!(
            "[package]\nname = \"root-pkg\"\nversion = \"0.1.0\"\n\n[workspace]\n\n[dependencies]\nhelper = {{ path = \"{}\" }}\nserde = \"1\"\n",
            in_tree.display(),
        ),
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    fs::write(repo.join("src/lib.rs"), "pub fn r() {}\n").expect("lib");
    fs::write(
        repo.join("crates/helper/Cargo.toml"),
        "[package]\nname = \"helper\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("helper manifest");
    fs::write(repo.join("crates/helper/src/lib.rs"), "pub fn h() {}\n").expect("lib");

    let rel_repo = relative_path_from_cwd(&repo);
    assert!(
        rel_repo.is_relative(),
        "fixture must exercise a relative scan root"
    );
    assert!(
        rel_repo.join("Cargo.toml").is_file(),
        "relative repo path must resolve from the test working directory"
    );

    let jsonl = scan_repository_at_with_override(&rel_repo, FIXED_TIME, Some("rel-root-fixture"))
        .expect("scan must not fail on a relative repo root")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    let helper = declarations
        .iter()
        .find(|d| d["declaring_package"] == "helper")
        .expect("helper row");
    assert_eq!(
        helper["resolution"], "locked",
        "an absolute in-tree path dependency is a member even under a relative scan root"
    );
    assert_eq!(helper["resolved_version"], "1.0.228");
}

/// PR #314 review: Cargo's `members`/`exclude` globs support character
/// classes (the `glob` crate — `[ab]`, ranges, `[!…]`). A class in `members`
/// must admit the member and a class in `exclude` must be honored.
#[test]
fn workspace_glob_character_classes_are_honored() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    for member in ["a", "b"] {
        fs::create_dir_all(repo.join(format!("crates/{member}/src"))).expect("dirs");
        fs::write(
            repo.join(format!("crates/{member}/Cargo.toml")),
            format!(
                "[package]\nname = \"pkg-{member}\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n"
            ),
        )
        .expect("member manifest");
        fs::write(
            repo.join(format!("crates/{member}/src/lib.rs")),
            "pub fn f() {}\n",
        )
        .expect("lib");
    }
    fs::write(
        repo.join("Cargo.toml"),
        "[workspace]\nmembers = [\"crates/[ab]\"]\nexclude = [\"crates/[b]\"]\n",
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("class-glob-fixture"))
        .expect("scan must not fail on class globs")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    let pkg_a = declarations
        .iter()
        .find(|d| d["declaring_package"] == "pkg-a")
        .expect("pkg-a row");
    assert_eq!(
        pkg_a["resolution"], "locked",
        "a member admitted by a class glob resolves from the root lockfile"
    );
    assert_eq!(pkg_a["resolved_version"], "1.0.228");
    let pkg_b = declarations
        .iter()
        .find(|d| d["declaring_package"] == "pkg-b")
        .expect("pkg-b row");
    assert_eq!(
        pkg_b["resolution"], "no_lockfile",
        "an exclude entry written as a class glob is honored"
    );
}

/// Builds a workspace-root package that path-depends on an excluded package,
/// which in turn path-depends on `crates/helper`. When `root_also_depends_on_helper`
/// is set, the root additionally depends on the helper directly, making it
/// independently reachable outside the excluded chain.
fn excluded_chain_graph(root_also_depends_on_helper: bool) -> (tempfile::TempDir, PathBuf) {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("crates/excluded/src")).expect("dirs");
    fs::create_dir_all(repo.join("crates/helper/src")).expect("dirs");
    fs::create_dir_all(repo.join("src")).expect("dirs");
    let helper_dep = if root_also_depends_on_helper {
        "helper = { path = \"crates/helper\" }\n"
    } else {
        ""
    };
    fs::write(
        repo.join("Cargo.toml"),
        format!(
            "[package]\nname = \"root-pkg\"\nversion = \"0.1.0\"\n\n[workspace]\nexclude = [\"crates/excluded\"]\n\n[dependencies]\nexcluded = {{ path = \"crates/excluded\" }}\n{helper_dep}serde = \"1\"\n"
        ),
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    fs::write(repo.join("src/lib.rs"), "pub fn r() {}\n").expect("lib");
    fs::write(
        repo.join("crates/excluded/Cargo.toml"),
        "[package]\nname = \"excluded\"\nversion = \"0.1.0\"\n\n[dependencies]\nhelper = { path = \"../helper\" }\nserde = \"1\"\n",
    )
    .expect("excluded manifest");
    fs::write(repo.join("crates/excluded/src/lib.rs"), "pub fn e() {}\n").expect("lib");
    fs::write(
        repo.join("crates/helper/Cargo.toml"),
        "[package]\nname = \"helper\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("helper manifest");
    fs::write(repo.join("crates/helper/src/lib.rs"), "pub fn h() {}\n").expect("lib");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("excluded-chain"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");
    (temp, graph)
}

/// PR #314 review: `exclude` removes the package AND everything reachable
/// only through it — Cargo makes neither the excluded package nor its
/// transitive path dependencies workspace members. The closure must not
/// traverse an excluded directory's manifest.
#[test]
fn excluded_packages_never_extend_the_membership_closure() {
    let (_temp, graph) = excluded_chain_graph(false);
    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    let by_pkg = |pkg: &str| {
        declarations
            .iter()
            .find(|d| d["declaring_package"] == pkg)
            .unwrap_or_else(|| panic!("row for {pkg}"))
    };
    assert_eq!(by_pkg("root-pkg")["resolution"], "locked");
    assert_eq!(
        by_pkg("excluded")["resolution"],
        "no_lockfile",
        "an excluded path dependency is standalone, never a member"
    );
    assert_eq!(
        by_pkg("helper")["resolution"],
        "no_lockfile",
        "a package reachable only through an excluded one is not a member either"
    );
}

/// A transitive dependency of an excluded package that is ALSO reachable
/// from a non-excluded seed keeps its membership through that other path.
#[test]
fn independently_reachable_deps_survive_an_excluded_sibling_chain() {
    let (_temp, graph) = excluded_chain_graph(true);
    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    let by_pkg = |pkg: &str| {
        declarations
            .iter()
            .find(|d| d["declaring_package"] == pkg)
            .unwrap_or_else(|| panic!("row for {pkg}"))
    };
    assert_eq!(
        by_pkg("helper")["resolution"],
        "locked",
        "the root's own direct path dependency stays a member"
    );
    assert_eq!(by_pkg("helper")["resolved_version"], "1.0.228");
    assert_eq!(
        by_pkg("excluded")["resolution"],
        "no_lockfile",
        "the excluded package itself stays out"
    );
}

/// PR #314 review: Cargo treats target-specific path dependencies
/// (`[target.'cfg(unix)'.dependencies] helper = { path = "…" }`) as
/// automatic workspace members too. The membership closure must scan target
/// tables for `path` entries even though target-specific dependency ROWS
/// stay out of extraction scope.
#[test]
fn target_specific_path_dependencies_join_the_workspace() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("app/src")).expect("dirs");
    fs::create_dir_all(repo.join("helper/src")).expect("dirs");
    fs::write(
        repo.join("Cargo.toml"),
        "[workspace]\nmembers = [\"app\"]\n",
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    fs::write(
        repo.join("app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n\n[target.'cfg(unix)'.dependencies]\nhelper = { path = \"../helper\" }\n",
    )
    .expect("app manifest");
    fs::write(repo.join("app/src/lib.rs"), "pub fn a() {}\n").expect("lib");
    fs::write(
        repo.join("helper/Cargo.toml"),
        "[package]\nname = \"helper\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("helper manifest");
    fs::write(repo.join("helper/src/lib.rs"), "pub fn h() {}\n").expect("lib");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("target-dep-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    let helper = declarations
        .iter()
        .find(|d| d["declaring_package"] == "helper")
        .expect("helper row");
    assert_eq!(
        helper["resolution"], "locked",
        "a target-specific path dependency is an automatic workspace member"
    );
    assert_eq!(helper["resolved_version"], "1.0.228");
    // Target-specific dependency ROWS stay out of extraction scope: app
    // declares only its plain-table serde, never a `helper` fact.
    let all_rows = run_query_deps(&graph, &[]);
    assert!(
        !all_rows["declarations"]
            .as_array()
            .expect("declarations")
            .iter()
            .any(|d| d["declaring_package"] == "app" && d["name"] == "helper"),
        "target-specific dependency rows are not extracted"
    );
}

/// PR #314 review: a member declaring `helper = { workspace = true }` where
/// the root's `[workspace.dependencies]` maps `helper` to a `path` makes the
/// helper an automatic workspace member per Cargo — the closure must resolve
/// inherited entries against the root table (paths relative to the ROOT).
/// The root package's own inherited entries count too.
#[test]
fn workspace_inherited_path_dependencies_join_the_workspace() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    for dir in ["app/src", "helper/src", "helper2/src", "src"] {
        fs::create_dir_all(repo.join(dir)).expect("dirs");
    }
    // Root is BOTH a workspace root and a package: the member inherits
    // `helper`, the root package itself inherits `helper2`.
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"root-pkg\"\nversion = \"0.1.0\"\n\n[workspace]\nmembers = [\"app\"]\n\n[workspace.dependencies]\nhelper = { path = \"helper\" }\nhelper2 = { path = \"helper2\" }\n\n[dependencies]\nserde = \"1\"\nhelper2 = { workspace = true }\n",
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    fs::write(repo.join("src/lib.rs"), "pub fn r() {}\n").expect("lib");
    fs::write(
        repo.join("app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\nhelper = { workspace = true }\n",
    )
    .expect("app manifest");
    fs::write(repo.join("app/src/lib.rs"), "pub fn a() {}\n").expect("lib");
    for (dir, pkg) in [("helper", "helper"), ("helper2", "helper2")] {
        fs::write(
            repo.join(dir).join("Cargo.toml"),
            format!(
                "[package]\nname = \"{pkg}\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n"
            ),
        )
        .expect("helper manifest");
        fs::write(repo.join(dir).join("src/lib.rs"), "pub fn h() {}\n").expect("lib");
    }

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("inherited-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    let by_pkg = |pkg: &str| {
        declarations
            .iter()
            .find(|d| d["declaring_package"] == pkg)
            .unwrap_or_else(|| panic!("row for {pkg}"))
    };
    assert_eq!(
        by_pkg("helper")["resolution"],
        "locked",
        "a member's workspace-inherited path dependency is an automatic member"
    );
    assert_eq!(by_pkg("helper")["resolved_version"], "1.0.228");
    assert_eq!(
        by_pkg("helper2")["resolution"],
        "locked",
        "the root package's own workspace-inherited path dependency counts too"
    );
    assert_eq!(by_pkg("helper2")["resolved_version"], "1.0.228");
}

/// Pin (Cargo semantics): a `[workspace.dependencies]` path entry that no
/// member (and not the root package) ever inherits is only a template — it
/// does NOT make the target directory a workspace member.
#[test]
fn uninherited_workspace_dependency_paths_are_not_members() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    for dir in ["app/src", "ghost/src"] {
        fs::create_dir_all(repo.join(dir)).expect("dirs");
    }
    fs::write(
        repo.join("Cargo.toml"),
        "[workspace]\nmembers = [\"app\"]\n\n[workspace.dependencies]\nghost = { path = \"ghost\" }\n",
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    fs::write(
        repo.join("app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("app manifest");
    fs::write(repo.join("app/src/lib.rs"), "pub fn a() {}\n").expect("lib");
    fs::write(
        repo.join("ghost/Cargo.toml"),
        "[package]\nname = \"ghost\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("ghost manifest");
    fs::write(repo.join("ghost/src/lib.rs"), "pub fn g() {}\n").expect("lib");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("uninherited-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    let ghost = declarations
        .iter()
        .find(|d| d["declaring_package"] == "ghost")
        .expect("ghost row");
    assert_eq!(
        ghost["resolution"], "no_lockfile",
        "an uninherited workspace-dependencies path entry is only a template, never a member"
    );
}

/// PR #314 review: a valid-TOML manifest with dependency tables but no
/// usable `[package].name` cannot attribute its declarations — a silent
/// skip would be a coverage hole, so it surfaces as a `skipped_manifest`
/// diagnostic qualifying every answer (including a `--name` miss).
#[test]
fn nameless_manifest_dependencies_surface_as_skipped_manifest() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    fs::create_dir_all(repo.join("src")).expect("dirs");
    fs::create_dir_all(repo.join("noname")).expect("dirs");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"root-pkg\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n",
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");
    fs::write(repo.join("src/lib.rs"), "pub fn r() {}\n").expect("lib");
    // Valid TOML, declares dependencies, but no [package].name.
    fs::write(
        repo.join("noname/Cargo.toml"),
        "[package]\nversion = \"0.1.0\"\n\n[dependencies]\ntokio = \"1\"\n",
    )
    .expect("nameless manifest");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("nameless-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    // A --name miss for the crate hidden behind the nameless manifest is
    // qualified, never a silently definitive "no".
    let parsed = run_query_deps(&graph, &["--name", "tokio"]);
    assert_eq!(parsed["count"], 0);
    let diagnostics = skipped_diagnostics(&parsed);
    assert_eq!(
        diagnostics.len(),
        1,
        "the unattributable manifest must surface as a coverage hole"
    );
    assert_eq!(diagnostics[0]["detail"], "noname/Cargo.toml");

    // The full listing carries the same qualification.
    let full = run_query_deps(&graph, &[]);
    assert_eq!(skipped_diagnostics(&full).len(), 1);
}

/// PR #314 review: Cargo accepts `./`-prefixed `members`/`exclude` entries
/// (`members = ["./crates/*"]`); the matcher must normalize `.` segments so
/// such members resolve from the root lockfile and `./` excludes are honored.
#[test]
fn dot_prefixed_member_and_exclude_globs_are_honored() {
    let temp = tempfile::tempdir().expect("temp dir");
    let repo = temp.path().join("repo");
    for member in ["a", "b"] {
        fs::create_dir_all(repo.join(format!("crates/{member}/src"))).expect("dirs");
        fs::write(
            repo.join(format!("crates/{member}/Cargo.toml")),
            format!(
                "[package]\nname = \"pkg-{member}\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde = \"1\"\n"
            ),
        )
        .expect("member manifest");
        fs::write(
            repo.join(format!("crates/{member}/src/lib.rs")),
            "pub fn f() {}\n",
        )
        .expect("lib");
    }
    fs::write(
        repo.join("Cargo.toml"),
        "[workspace]\nmembers = [\"./crates/*\"]\nexclude = [\"./crates/b\"]\n",
    )
    .expect("root manifest");
    fs::write(
        repo.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.228\"\n",
    )
    .expect("root lockfile");

    let jsonl = scan_repository_at_with_override(&repo, FIXED_TIME, Some("dot-glob-fixture"))
        .expect("fixture should scan")
        .to_jsonl()
        .expect("graph should serialize");
    let graph = temp.path().join("graph.jsonl");
    fs::write(&graph, jsonl).expect("write graph");

    let parsed = run_query_deps(&graph, &["--name", "serde"]);
    let declarations = parsed["declarations"].as_array().expect("declarations");
    let by_pkg = |pkg: &str| {
        declarations
            .iter()
            .find(|d| d["declaring_package"] == pkg)
            .unwrap_or_else(|| panic!("row for {pkg}"))
    };
    assert_eq!(
        by_pkg("pkg-a")["resolution"],
        "locked",
        "a ./-prefixed members glob admits the member"
    );
    assert_eq!(by_pkg("pkg-a")["resolved_version"], "1.0.228");
    assert_eq!(
        by_pkg("pkg-b")["resolution"],
        "no_lockfile",
        "a ./-prefixed exclude entry is honored"
    );
}
